extends: airbnb-base

env:
  browser: true
  mocha: true

globals:
  Ext: true
  expect: true
  Ext6KarmaMocha: true

rules:
  comma-dangle: 0
  object-shorthand: 0
  func-names: 0
  prefer-arrow-callback: 0
